# Generated by Django 5.1.7 on 2025-03-11 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='board',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
